# =====================================================
# Configuração MkDocs para GitHub Pages - SoftSkills
# =====================================================

site_name: "SoftSkills"
site_description: "Documentação SoftSkills"
site_author: "Matheus Moraes"
site_url: "https://MatheusMoraes.github.io/SoftSkills/"  # URL do GitHub Pages
use_directory_urls: true

theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: deep purple
      accent: lime
      toggle:
        icon: material/weather-night
        name: Modo escuro
    - scheme: slate
      primary: deep purple
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  font:
    text: Roboto
    code: JetBrains Mono
  logo: images/favicon.png
  favicon: images/favicon.png

plugins:
  - search
  - roamlinks

markdown_extensions:
  - footnotes
  - tables
  - admonition
  - toc:
      permalink: true

nav:
  - Arte de facilitar reuniões: arte_de_facilitar_reunioes.md
  - A tão temida pauta: a_tao_temida_pauta.md
  - Encerramento: encerramento.md
  - Notas: notas.md

extra_css:
  - styles/extra.css

# =====================================================
# Diretório de saída do build (geralmente já é 'site')
# =====================================================
site_dir: site

# =====================================================
# Configurações de deploy com MkDocs/GitHub Pages
# =====================================================
# Com isso, o mkdocs gh-deploy --force publica na branch gh-pages
# garantindo que index.html esteja na raiz e todos os assets funcionem.
# A branch e token são configurados no workflow do GitHub Actions.
# =====================================================
