name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # dispara quando você dá push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Fazer checkout do repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3️⃣ Cache do pip para acelerar instalações
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4️⃣ Instalar dependências
      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-roamlinks-plugin

      # 5️⃣ Build do site MkDocs
      - name: Build MkDocs site
        run: mkdocs build

      # 6️⃣ Deploy para GitHub Pages usando peaceiris action
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true  # força criação da branch se não existir